#!/bin/sh

juju-log "lamp - shared-db: Relation CHANGED"
myuser=`config-get database-user`
mydatabase=`config-get website-database`

#get informations from db
remote_host=`relation-get private-address`
password=`relation-get password`
juju-log "remote host is $remote_host"
if [ -z "$remote_host" ] || [ -z "$password" ]; then
	juju-log "Waiting for complete setup"
	exit 0
fi

# Build config file to hold configuration options
juju-log "Building config file for $host"
cat > "config/$remote_host" <<EOF
#!/bin/sh

server_name=${JUJU_REMOTE_UNIT%%/*}
server_user=${myuser}
server_pass=${password}
server_db=${mydatabase}
EOF
#
#creating file pointing to last configuration 
cat > "config/mysql" <<EOF
server_ip=${remote_host}
EOF
#

#building the database
juju-log "Building $database database on $host"
mysql -h $remote_host -u $myuser --password=$password $mydatabase < ./config/mysql_conf

#setting up configuration files to be accessible by apache process
cp ./config/* /var/webconfig
chown -R www-data:www-data ./config
chown -R www-data:www-data /var/webconfig
chmod 640 ./config/*
chmod 640 /var/webconfig/*
