#!/bin/sh

BZR_BRANCH=`config-get website-bzr`
juju-log "updating packages"
apt-get update -y

#restart apache
service apache2 restart

#copy php files to directory
if ls ./website/* > /dev/null 2>&1; then
 cp -r ./website/* /var/www
 chown -R www-data:www-data /var/www
fi

#update bzr branch 
if [ ! -z "$BZR_BRANCH" ]; then
 juju-log "pulling latest version of $bzr_current"
 cd website 
 bzr pull
 cd ..
 cp website/mysql_conf config
 cp website/* /var/www/ -r
 chown -R www-data:www-data /var/www
fi

