#!/bin/sh

set -e
BZR_BRANCH=`config-get website-bzr`
BZR_PULL=`config-get bzr-update`

#restart apache
service apache2 restart

#copy php files to directory
if ls ./website/* > /dev/null 2>&1; then
 cp -r ./website/* /var/www
 chown -R www-data:www-data /var/www
fi

#update bzr branch 
if [ ! -z "$BZR_BRANCH" ] && [ ! -z "$BZR_PULL" ]; then
 juju-log "pulling latest version of $BZR_BRANCH"
 cd website 
 bzr pull
 cd ..
 cp website/mysql_conf config
 rm -r /var/www/*
 cp -r website/* /var/www/
 chown -R www-data:www-data /var/www
fi

